# Generated by Django 5.2.9 on 2025-12-16 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.IntegerField(db_index=True, help_text='Первые 3 цифры номера (без 7/8)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Код ABC/DEF')),
                ('start_range', models.IntegerField(db_index=True, help_text='Начало диапазона в формате хвоста от 1 до 7 знаков', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Начало диапазона')),
                ('end_range', models.IntegerField(db_index=True, help_text='Конец диапазона в формате хвоста от 1 до 7 знаков', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Конец диапазона')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Емкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор связи')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('territory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Территория ГАР')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Диапазон номеров',
                'verbose_name_plural': 'Диапазоны номеров',
                'indexes': [models.Index(fields=['abc', 'start_range', 'end_range'], name='core_phoner_abc_04405d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_range__lte', models.F('end_range'))), name='start_lte_end')],
            },
        ),
    ]
